import { StyleSheet } from 'react-native';

export const appUpdateModalColors = {
  overlay: 'rgba(0, 0, 0, 0.62)',
  surface: '#1f232b',
  nested: '#111827',
  border: '#303742',
  text: '#f8fafc',
  muted: '#9ca3af',
  primary: '#8b5cf6',
  success: '#22c55e',
  info: '#38bdf8',
  danger: '#ef4444',
};

export const appUpdateModalStyles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: appUpdateModalColors.overlay,
    zIndex: 9000,
    elevation: 9000,
  },
  dialog: {
    width: '100%',
    maxHeight: '88%',
    alignSelf: 'center',
    maxWidth: 460,
    backgroundColor: appUpdateModalColors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
    padding: 18,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  iconContainer: {
    width: 42,
    height: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: appUpdateModalColors.text,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  subtitle: {
    color: appUpdateModalColors.muted,
    fontSize: 13,
    marginTop: 2,
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconMuted: {
    color: appUpdateModalColors.muted,
  },
  iconDisabled: {
    color: '#4b5563',
  },
  body: {
    flexShrink: 1,
  },
  bodyContent: {
    paddingBottom: 2,
  },
  releaseSummary: {
    backgroundColor: appUpdateModalColors.nested,
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
    gap: 6,
  },
  versionPill: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: appUpdateModalColors.primary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  versionText: {
    color: appUpdateModalColors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  releaseName: {
    color: appUpdateModalColors.text,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
  },
  releaseMeta: {
    color: appUpdateModalColors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  notesContainer: {
    marginBottom: 16,
  },
  notesTitle: {
    color: appUpdateModalColors.text,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  notesScroll: {
    maxHeight: 220,
    minHeight: 96,
    backgroundColor: appUpdateModalColors.nested,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
  },
  notesContent: {
    padding: 14,
  },
  notesText: {
    color: appUpdateModalColors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  markdownContainer: {
    gap: 8,
  },
  markdownHeading: {
    color: appUpdateModalColors.text,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
    marginTop: 4,
  },
  markdownSubheading: {
    color: appUpdateModalColors.text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
    marginTop: 4,
  },
  markdownBody: {
    color: appUpdateModalColors.text,
    fontSize: 14,
    lineHeight: 21,
    flex: 1,
  },
  markdownBold: {
    fontWeight: '700',
  },
  markdownItalic: {
    fontStyle: 'italic',
  },
  markdownCode: {
    fontFamily: 'monospace',
    color: appUpdateModalColors.info,
    fontSize: 13,
  },
  markdownLink: {
    color: appUpdateModalColors.primary,
    textDecorationLine: 'underline',
  },
  markdownBulletRow: {
    flexDirection: 'row',
    gap: 8,
  },
  markdownBulletMarker: {
    color: appUpdateModalColors.primary,
    fontSize: 14,
    lineHeight: 21,
  },
  markdownCodeBlock: {
    backgroundColor: appUpdateModalColors.surface,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
    padding: 8,
  },
  markdownCodeBlockText: {
    color: appUpdateModalColors.muted,
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 17,
  },
  markdownRule: {
    height: 1,
    backgroundColor: appUpdateModalColors.border,
    marginVertical: 4,
  },
  messageBox: {
    backgroundColor: '#2a1719',
    borderWidth: 1,
    borderColor: '#7f1d1d',
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
  },
  errorText: {
    color: appUpdateModalColors.danger,
    fontSize: 14,
    lineHeight: 20,
  },
  infoMessageBox: {
    backgroundColor: '#0b2230',
    borderColor: '#155e75',
  },
  infoText: {
    color: appUpdateModalColors.info,
    fontSize: 14,
    lineHeight: 20,
  },
  progressPanel: {
    backgroundColor: appUpdateModalColors.nested,
    borderWidth: 1,
    borderColor: appUpdateModalColors.primary,
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
    gap: 10,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  progressTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  progressTitle: {
    color: appUpdateModalColors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  progressPercent: {
    color: appUpdateModalColors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: appUpdateModalColors.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: appUpdateModalColors.primary,
  },
  progressMeta: {
    color: appUpdateModalColors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  actions: {
    gap: 10,
    paddingTop: 10,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modalButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  primaryButton: {
    backgroundColor: appUpdateModalColors.primary,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
  },
  disabledButton: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButtonText: {
    color: appUpdateModalColors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  skipButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: '#171b22',
    borderWidth: 1,
    borderColor: appUpdateModalColors.border,
    paddingHorizontal: 14,
  },
  skipButtonText: {
    color: appUpdateModalColors.muted,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
});
