import type { SecurityActionType } from '../model/types';

export const authCopy = {
  forgotPassword: {
    sendCode: 'Send Code',
    alreadyHaveCode: 'Already have a code?',
    verifyCode: 'Verify Code',
    needNewCode: 'Need a new code?',
    codeSent: 'Verification code sent. Check your email for the code.',
    codeVerified: 'Code verified. Set a new password.',
    sendCodeFailed: 'Could not send the verification code. Check your email and try again.',
    verifyCodeFailed: 'Could not verify that code. Check it and try again.',
  },
  resetPassword: {
    tempTokenMissing: 'Reset session is missing.',
    passwordTooShort: 'Password must be at least 6 characters.',
    passwordMismatch: 'Passwords do not match.',
    success: 'Password reset. Please sign in again.',
    failed: 'Could not reset your password. Please try again.',
  },
  security: {
    googlePrompt: "You'll be prompted to authenticate with Google",
    actionUnavailable: 'This action is not available for your sign-in method on this platform.',
    passwordUnavailable: 'Password change is not available for your sign-in method.',
    googleLinkedEmailAndroid: 'To change this email, unlink Google first, update the email, then link Google again.',
    googleLinkedEmailIos: 'Email change is not available on iOS while Google is linked.',
    incorrectPassword: 'Incorrect password',
    failed: (actionLabel: string) => `Failed to ${actionLabel.toLowerCase()}`,
    buttonText: {
      delete: 'Delete Account',
      password: 'Change Password',
      email: 'Change Email',
    } satisfies Record<SecurityActionType, string>,
    success: {
      delete: 'Account deleted successfully!',
      password: 'Password changed successfully!',
      email: 'Email changed successfully!',
    } satisfies Record<SecurityActionType, string>,
    validation: {
      currentPasswordRequired: 'Password is required',
      newPasswordRequired: 'New password is required',
      minimumPasswordLength: 'Minimum 6 characters',
      confirmPassword: 'Please confirm password',
      passwordsMustMatch: 'Passwords must match',
      passwordMustChange: 'New password must be different',
      newEmailRequired: 'New email is required',
      invalidEmail: 'Invalid email format',
      confirmEmail: 'Please confirm email',
      emailsMustMatch: 'Emails must match',
      emailMustChange: 'New email must be different',
    },
  },
  menu: {
    linkGooglePrompt: 'Link your Google account to this profile?',
    linkGoogleSuccess: 'Google account has been linked to your profile',
    linkGoogleFailed: 'Failed to link Google account.',
    linkPasswordSuccess: 'Password sign-in has been linked to your account',
    linkPasswordFailed: 'Failed to link password.',
    unlinkOnlyProvider: 'You cannot unlink your only sign-in method. Add another sign-in method first.',
    unlinkGooglePrompt: 'Unlink Google from this profile? You will still be able to sign in with another method.',
    unlinkGoogleSuccess: 'Google account has been unlinked from your profile',
    unlinkGoogleFailed: 'Failed to unlink Google account.',
    unlinkPasswordPrompt: 'Unlink password sign-in from this profile? You will still be able to sign in with another method.',
    unlinkPasswordSuccess: 'Password sign-in has been unlinked from your profile',
    unlinkPasswordFailed: 'Failed to unlink password sign-in.',
  },
};
